# имя workflow
name: Publish Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# workflow - набор jobs, т.е. их мб неск
jobs:
# название job'а
  build:
# на чем запускается
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
# параметры uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: docker.pkg.github.com
# репозиторий/мое имя на гитхабе/репозиторий проекта/название пакета, которй формируется внутри
          name: docker.pkg.github.com/alaricode/top-app-demo/top-app-demo
# username и password указваются на гитхабе: настройки-секреты-секреты репозитория
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
# в продакшене обчно указвают версии приложения (проекта)
          tags: "develop"
